### ISSUE TITLE
Type error 'this.reporter.registerTestError is not a function' appears sporadically on expect.element('@elementName').text.to.conains(text) using Node 10.15.3

### ISSUE THREAD

**Issue by sanjapa** [mucsi96/nightwatch-api#493]
Sometimes, but not always (mostly when tests are run from CI - team city on browserStack), the following error appear on this.expect.element('@nameOfTheElement').text.to.contains(text).
`Error while running "getText" command: this.reporter.registerTestError is not a function TypeError: Error while running "getText" command: this.reporter.registerTestError is not a function at transport.locateElement.then.then.catch.result (/nightwatch/node_modules/nightwatch/lib/api loader/element-command.js:138:25)at process._tickCallback (internal/process/next_tick.js:68:7)`

**Please note that this started to happen after I update npm to 6.9.0. On previous version 6.5.0 this is not reproducible**

I am using Nightwatch-API with Cucumber.
Nightwatch version : 1.0.19
Nightwatch-api version: 2.1.3
Node version: 10.15.3
Npm version: 6.9.0
Selenium server version: 3.141.59

**Comment by RavikiranHannurkar** [comment]
I am also facing same issue. It stops execution and doesn't generate report(cucumber.json) when it fails.

**Comment by inavac182** [comment]
I have been facing the same issue when I try to getAttributes, getText, click in an element that is not present. I think it should have some kind of safe to validate that element is not found instead of breaking the entire execution.

**Comment by spnraju** [comment]
Hey @sanjapa , @RavikiranHannurkar and @inavac182 , Thank you for reporting this with details. This seem to be a issue with nightwatch itself. We will take a look and get back to you. Please share if there are any sample repos or code where we can easily reproduce this.

**Comment by inavac182** [comment]
Hey @spnraju, thanks for taking a look!  I will try to explain what I'm seeing.

So, in my case this is how I was able to repro this constantly in this scenario:

I have a step that click in an link and if this element has true in a specific attribute then we have to click in a 2nd element, in order to move to the next page. But if the attribute is false, then the page move to the next page automatically.

This is how the code looks:

const mySection = browser.section.mySection; 
const needSecondClick;

await mySection.waitForElementPresent('@myElement', 5000); 
await mySection.click('@myElement');  
await mySection.getAttribute('@myElement', 'my-attribute', attr => {
      needSecondClick = attr.value;
}); 

if (needSecondClick) {
  await mySection.click('@mySecondaryElement');  
}

So, the issue is when in the first click we move to the next page the function getAttribute fails because the element is not present, which is ok but instead of showing the test error of element not found, is breaking with the issue, which makes hard to debug and understand what is wrong in the test:

```
Error while running "getAttribute" command: this.reporter.registerTestError is not a function
TypeError: Error while running "getAttribute" command: this.reporter.registerTestError is not a function
    at GetAttribute.handleElementError (....node_modules/nightwatch/lib/api/element-commands/_baseElementCommand.js:89:21)
    at GetAttribute.elementNotFound (....node_modules/nightwatch/lib/api/element-commands/_baseElementCommand.js:61:17)
    at GetAttribute.elementLocateError (....node_modules/nightwatch/lib/element/command.js:182:19)
    at GetAttribute.actionErrorHandler (.....node_modules/nightwatch/lib/element/command.js:113:17)
    at Object.errorHandler (.....node_modules/nightwatch/lib/api/element-commands/_baseElementCommand.js:40:23)
    at PeriodicPromise.runAction (......node_modules/nightwatch/lib/util/periodic-promise.js:60:29)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Please let me know if you need more info.

**Comment by spnraju** [comment]
Hi @inavac182 Thank you for these details. We will look into this. Meanwhile, can you guys confirm if you are all on same version of nightwatch and nightwatch-api?

**Comment by mucsi96** [comment]
Should be fixed in https://github.com/mucsi96/nightwatch-api/pull/494. Please review.

**Comment by mucsi96** [comment]
During debugging I noticed a very strange error handling in Nightwatch
![image](https://user-images.githubusercontent.com/3163392/57587225-ee9a0880-7501-11e9-97b0-8fdaefba81f2.png)
So basically the user is responsible for proper error handling inside the callback function to achieve proper error propagation.

So the correct usage of `getAttribute` method is the following
![image](https://user-images.githubusercontent.com/3163392/57587237-302ab380-7502-11e9-96e8-508a39d4daa0.png)

I find it very inconvenient. What do you think?

**Comment by spnraju** [comment]
@mucsi96 Maybe can we get this to beatfactor from nightwatch's attention?

**Comment by mucsi96** [comment]
Yeah will do so. The fix is released as part of version `2.2.1`

**Comment by RavikiranHannurkar** [comment]
Thank you @mucsi96  and @spnraju for fixing this issue.
Just one question: will it solve issue of 'this.reporter.registerTestError' error in all conditions?

because I was getting this issue not just for 'expect.element' or '.getAttribute' but also for '.click' also.
When element is not visible on page and '.click' fails it shows error 'Error while running "click" command: this.reporter.registerTestError is not a function' 

Because of this issue some time it stops whole test execution and doesn't generate test report.

I am just wondering, is this a separate issue or it is a same issue that will be fixed by #494

**Comment by mucsi96** [comment]
Yes it should be fixed everywhere. We are waiting your feedback on this.

**Comment by beatfactor** [comment]
> During debugging I noticed a very strange error handling in Nightwatch

@mucsi96 @spnraju could you try to upgrade to nightwatch@1.1.8? Error handling should be improved there.

**Comment by mucsi96** [comment]
Hi @beatfactor! Thank you for your kind contribution! We will do so

**Comment by RavikiranHannurkar** [comment]
@mucsi96 It seems to be fixed for me. Executed whole test pack 3 time and it is working fine.
Thank you so much !

**Comment by mucsi96** [comment]
Great! Thank you for submitting the issue!

**Comment by inavac182** [comment]
Yeah, works fine now in my scenario 👍
